### ISSUE TITLE
Add support to plugins

### ISSUE THREAD

**Issue by duviful** [jvoss/ansible-role-netbox#27]
Hello dear sir.
it would be nice to add custom plugins to `local_requirements.txt` and install them automatically.

a task in the file `configure.yml` similar to this one can do the job:

```yaml
- name: configure | add the custom plugins local_requirements.txt
  ansible.builtin.lineinfile:
    path: "{{ netbox_current_path }}/local_requirements.txt"
    line: "{{ item.name }}"
    regexp: "^{{ item.name }}"
    owner: "{{ netbox_user }}"
    mode: '0644'
    create: yes
  with_items: "{{ netbox_plugins }}"
```

I'm using the already present variable `netbox_plugins` to generate the list of names to be added to the `local_requirements.txt`

I might open a PR but I suspect you are already working on something like this.
let me know.

Best
