### ISSUE TITLE
Add support for Debian Bookworm

### ISSUE THREAD

**Issue by jvoss** [jvoss/ansible-role-netbox#65]
Add the following to support Debian bookworm:

`vars/Debian-12.yml`:
```yaml
---
__python_version: "3.11"
__python_packages:
    - "python{{ python_version | default(__python_version) }}"
    - "python3-pip"
    - "python{{ python_version | default(__python_version) }}-venv"
    - "python{{ python_version | default(__python_version) }}-dev"
```
